apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    teir: db
    compoenent: mongodb
spec:
  clusterIP: None
  ports:
    - port: 27017
      targetPort: 27017
      name: mongodb
  selector:
    project: roboshop
    teir: db
    compoenent: mongodb

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  namespace: roboshop
  labels:
    project: roboshop
    teir: db
    compoenent: mongodb
spec:
  replicas: 3
  selector:
    matchLabels:
      project: roboshop
      teir: db
      compoenent: mongodb
  serviceName: mongodb
  template:
    metadata:
      labels:
        project: roboshop
        teir: db
        compoenent: mongodb
    spec:
      containers:
        - name: mongodb
          image: dkrish194/mongodb:3.0.0
          volumeMounts:
            - mountPath: /var/krishna
              name: var-krishna
  volumeClaimTemplates:
    - metadata:
        name: var-krishna
        labels:
          project: roboshop
          teir: db
          compoenent: mongodb
      spec:
        storageClassName: "openebs-hostpath"
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "1Gi"
            
      
 

