apiVersion: v1
kind: Pod
metadata: 
  name: python-app
  labels: 
    project: ownshop
    component: frontend
spec: 
  containers:
    - name : python-app-red
      image: dkrish194/python-app:1.0.0
      ports:
        - containerPort: 5000
      env:
        - name: COLOR
          value: red
        - name: RELEASE
          value: "1"
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "64Mi"
          cpu: "250m"
       
          
        
          

        



