apiVersion: v1
kind: Pod
metadata:
  name: frontend
  labels:
    project: roboshop
    teir: frontend
    component: frontend
spec:
  volumes:
    - name: shared
      emptyDir: {}
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /var/logs/
          name: shared
      resources:
        requests:
          cpu: "100m"
          memory: "150Mi"
        limits:
          cpu: "100m"
          memory: "150Mi"
    - name: alphine
      image: ubuntu
      command: [ "sleep", "100000"]
      volumeMounts:
        - name: shared
          mountPath: /var/log-alphine
      resources:
        requests:
          cpu: "100m"
          memory: "150Mi"
        limits:
          cpu: "100m"
          memory: "150Mi"
  


    
        
  