apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    project: roboshop
    component: frontend
    app: catalogue
  namespace: roboshop
  annotations:
    kubernetes.io/change-cause: "gree-rel-3"
spec:
  replicas: 3
  selector:
    matchLabels:
      project: roboshop
      component: frontend
      app: catalogue

  template:
    metadata:
      labels:
        project: roboshop
        component: frontend
        app: catalogue

    spec:
      tolerations:
        - key: env
          operator: Equal
          value: prod
          effect: NoSchedule
      # affinity:
      #   nodeAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #       nodeSelectorTerms:
      #         - matchExpressions:
      #             - key: kubernetes.io/hostname
      #               operator: NotIn
      #               values:
      #                 - k3d-k3d-lab-cluster-agent-2-0-0

      affinity:
          podAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - redis-cache                   # another pod lanel,  attractive pod lebel for co locate
                topologyKey: kubernetes.io/hostname
          podAntiAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchExpressions:
                    - key: app
                      operator: NotIn       # don't use NotIn pod may go pending state
                      values:
                        - catalogue          # same pod label,  for spread pod across nodes
                topologyKey: kubernetes.io/hostname
      containers:
        - name: catalogue
          image: nginx:1.29.8
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "64Mi"
              cpu: "250m"




