apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::194893387098:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-rrvxSiczOKPK
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::194893387098:user/roboshop-trainee-krishna
      username: roboshop-trainee-krishna
      groups:
        - roboshop-trainee-podreader

kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-27T05:35:06Z"
  name: aws-auth
  namespace: kube-system


