apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roboshop-trainee-podreader
  namespace: roboshAQQop
  labels:
    project: roboshop
subjects:
  - kind: User
    name: roboshop-trainee-krishna
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: roboshop-trainee-podreader