apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: roboshop-trinee-podreader
  namespace: robosop
  labels:
    porject: roboshop
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - deployment
      - service
    verbs:
      - get
      - watch
      - list


